# Este archivo fue generado automáticamente por GitHub Actions.
# https://github.com/features/actions

name: Deploy to Firebase Hosting on PR
"on": pull_request
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
          channel: "stable"

      - name: Get dependencies
        working-directory: Frontend/turneros_app
        run: flutter pub get

      - name: Build web app
        working-directory: Frontend/turneros_app
        run: flutter build web --release

      - name: Deploy to Firebase Hosting Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FARMATURNOS }}"
          projectId: farmaturnos
          entryPoint: Frontend/turneros_app
