# Este archivo fue generado automáticamente por GitHub Actions.
# https://github.com/features/actions

name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
    paths:
      - "Frontend/turneros_app/**"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          channel: "stable"

      - name: Get dependencies
        working-directory: Frontend/turneros_app
        run: flutter pub get

      - name: Build web app
        working-directory: Frontend/turneros_app
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FARMATURNOS }}"
          channelId: live
          projectId: farmaturnos
          entryPoint: Frontend/turneros_app
