// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5z1BqnClJ6puVr6z2saJp3e0u1RgHGQI',
    appId: '1:228344336816:web:26ef8c898bd2d4e0c50675',
    messagingSenderId: '228344336816',
    projectId: 'farmaturnos',
    authDomain: 'farmaturnos.firebaseapp.com',
    storageBucket: 'farmaturnos.firebasestorage.app',
    measurementId: 'G-SHJQHH87SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuRtWk6ZpQTVD06-ZFmKOsO4CZmKvPoSU',
    appId: '1:228344336816:android:60ac2a2b60243a34c50675',
    messagingSenderId: '228344336816',
    projectId: 'farmaturnos',
    storageBucket: 'farmaturnos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbv5bVjtsFMCduvK4mhZbHg8GlyLBvRIc',
    appId: '1:228344336816:ios:6159425ef6e2854fc50675',
    messagingSenderId: '228344336816',
    projectId: 'farmaturnos',
    storageBucket: 'farmaturnos.firebasestorage.app',
    androidClientId:
        '228344336816-1pr1r3c11j4airmturl166vupjbdmsdf.apps.googleusercontent.com',
    iosClientId:
        '228344336816-lmfjrq7645hhtp7mqinu70c8metogr0n.apps.googleusercontent.com',
    iosBundleId: 'com.turneros.turnerosApp',
  );
}
